name: CI Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment (Java 17 or 21 depending on your project)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      # Step 3: Grant execute permissions to the Maven wrapper (mvnw)
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      
      # Step 4: Build the project and run integration tests
      - name: Run Integration Tests
        run: ./mvnw verify -Pintegration-tests

      # Step 5: Archive test results
      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
